name: peot
description: >-
  Peot (psalm errors over time) is a command line application used to analyse 
  the number of errors in a PHP application over time using the psalm static 
  analysis tool.
version: 0.5.0
repository: https://github.com/Andrew-Mackay/peot

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
 csv: ^4.1.0
 path: ^1.7.0
 equatable: ^1.2.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
